### PR TITLE
30 bug fix

### LINKED ISSUE #30: Fix minor launch issues
Rewrite help strings to be more descriptive when used with !help
Fix Remind command and update help string.

### PR DESCRIPTION
**Pull request by colinobriendev**
Sorry for number of commits.

Should cover and close #30 :
Updating helps
Ensuring last merge we forgot works with this update
Fixing Remind command up

### CODE REVIEW

File: src/main/java/com/bp3x/raidbot/commands/lfg/LFGCommand.java [hunk 1]
```diff
@@ -146,4 +145,14 @@ String formatDateTimeInput(String date, String time) {
         result = (dateStringBuilder + " " + timeStringBuilder).toUpperCase();
         return result;
     }
+
+    /**
+     * Construct StringBuilder for use when !help is called
+     * @return - Help message for LFGCommand
+     */
+    private StringBuilder buildHelpMessage() {
```
Comment (laurenbarry00) [inline src/main/java/com/bp3x/raidbot/commands/lfg/LFGCommand.java:153]: Should this just return the String directly?

File: src/main/java/com/bp3x/raidbot/commands/lfg/RemindCommand.java [hunk 2]
```diff
@@ -27,35 +29,51 @@ protected void execute(CommandEvent event) {
         log.info("Reminding for " + event.getArgs());
 
         String[] args = event.getArgs().split("\\s+");
-        if (args.length == 2) {
+        if (args.length == 2 && (args[1].equalsIgnoreCase("accepted") || args[1].equalsIgnoreCase("tentative"))) {
```
Comment (laurenbarry00) [inline src/main/java/com/bp3x/raidbot/commands/lfg/RemindCommand.java:32]: Maybe the accepted and tentative check should be done in a nested if statement? This way, the error messages can be a bit more descriptive. 
```
if (args.length == 2) {
    if (args[1] .equals("accepted") || args[1].equals("tentative")) {
        // do things
    } else {
        print("use accepted or tentative");
    }

} else { print("You're missing some args")```

File: src/main/java/com/bp3x/raidbot/commands/lfg/RemindCommand.java [hunk 3]
```diff
@@ -27,35 +29,51 @@ protected void execute(CommandEvent event) {
...
-                    }
-                } else if (args[0].equalsIgnoreCase("tentative")) {
-                    for (Member player : remindEvent.getTentativePlayers()) {
-                        reminderStringBuilder.append("<@!");
-                        reminderStringBuilder.append(player.getUser().getId());
-                        reminderStringBuilder.append(">");
-                        reminderStringBuilder.append(LFGConstants.TENTATIVE_EMOJI);
-                        reminderStringBuilder.append("\n");
-                    }
+                buildReminderString(remindEvent, event, reminderStringBuilder);
```
Comment (laurenbarry00) [inline src/main/java/com/bp3x/raidbot/commands/lfg/RemindCommand.java:38]: Should this method just return a String instead of modifying the stringbuilder?

File: src/main/java/com/bp3x/raidbot/commands/lfg/util/Event.java [hunk 4]
```diff
@@ -110,6 +110,16 @@ public enum EventPlayerStatus {
         TENTATIVE
     }
 
+    /**
+     * Return true if accepted or tentative participants exist on the event, false otherwise
+     * @return - boolean
+     */
+    public boolean getActiveParticipants() {
```
Comment (laurenbarry00) [inline src/main/java/com/bp3x/raidbot/commands/lfg/util/Event.java:117]: naming nit: `hasActiveParticipants` would be in line w/  the "is" or "has" boolean convention

File: src/main/java/com/bp3x/raidbot/commands/lfg/LFGConstants.java [hunk 5]
```diff
@@ -37,4 +37,19 @@ private LFGConstants(){}
     public static final String DECLINED_PLAYERS = "Declined Players:";
     public static final String TENTATIVE_PLAYERS = "Tentative Players:";
     public static final String BLANK_PLAYER_LIST = "[N/A]";
+
+    public static final String LFG_HELP_START = "Example:\n`!lfg dsc 1/1/2022 9:00pm`\n";
+
+    public static final String LFG_HELP_SHORT_NAMES = "\nShort names for events: \n" +
```
Comment (laurenbarry00) [inline src/main/java/com/bp3x/raidbot/commands/lfg/LFGConstants.java:43]: Can we build this string by iterating through all the events in the `event.json` as opposed to hard-coding it?

File: src/main/java/com/bp3x/raidbot/commands/lfg/RemindCommand.java [hunk 6]
```diff
@@ -27,35 +29,51 @@ protected void execute(CommandEvent event) {
...
+
+    private void buildReminderString(Event remindEvent, CommandEvent event, StringBuilder sb) {
+        String[] args = event.getArgs().split("\\s+");
+
+        if (args[1].equalsIgnoreCase("accepted")) {
+            for (Member player : remindEvent.getAcceptedPlayers()) {
+                sb.append("<@!");
+                sb.append(player.getUser().getId());
+                sb.append(">\n");
+                sb.append(LFGConstants.ACCEPTED_EMOJI);
```
Comment (laurenbarry00) [inline src/main/java/com/bp3x/raidbot/commands/lfg/RemindCommand.java:63]: how does this look w/ multiple players in the list? is it like: 

@playername ✅ 
@playername ✅ 
@playername ✅ 

and 

@playername ❓ 
@playername ❓ 
@playername ❓ 


I am looking in #command-spam in the bot test discord and it looks like the emoji is on a newline after the name, but maybe that is not correct considering you were just testing stuff.

**Review by laurenbarry00 — CHANGES_REQUESTED** [review]

File: src/main/java/com/bp3x/raidbot/commands/lfg/RemindCommand.java [hunk 7]
```diff
@@ -29,46 +29,40 @@ protected void execute(CommandEvent event) {
...
-            if (remindEvent != null) {
-                buildReminderString(remindEvent, event, reminderStringBuilder);
-                log.info("getActiveParticipants = " + remindEvent.getActiveParticipants());
-                if (remindEvent.getActiveParticipants()) {
-                    event.getChannel().sendMessage("Players reminded:\n" + reminderStringBuilder).queue();
-                }
-                else {
-                    event.getChannel().sendMessage("There are no players to remind.").queue();
+                if (remindEvent != null) {
+                    buildReminderString(remindEvent, event, reminderStringBuilder);
```
Comment (laurenbarry00) [inline src/main/java/com/bp3x/raidbot/commands/lfg/RemindCommand.java:39]: this is still passing the stringbuilder as opposed to just returning a string

**Review by laurenbarry00 — CHANGES_REQUESTED** [review]
